version: "3.8"
services:

  php:
    build:
      context: ./library_manager
      dockerfile: Dockerfile
      target: php
      args:
        - APP_ENV=${APP_ENV}
    env_file:
      - "./library_manager/.env"
    environment:
      - APP_ENV=${APP_ENV}
      - CONTAINER_ROLE=app
      - VIRTUA_HOST=library.localhost
    working_dir: /var/www
    volumes:
      - ./library_manager:/var/www
    ports:
      - 8000:8000
    networks:
      - laravel
    


  database:
    image: mariadb:latest
    #ports:
    #  - 3306:3306
    env_file:
      - "./library_manager/.env"
    environment:
      - MYSQL_DATABASE=library
      - MYSQL_USER=valami
      - MYSQL_PASSWORD=
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - db-data:/var/lib/mysql
      - ./db_logs:/var/log/mysql/error.log
      - ./db_logs:/var/log/mysql/general.log
      - ./db_logs:/var/log/mysql/slow_query.log
      - ./db_logs/logs:/var/log/mysql/logs
      - ./library_manager/mariadb/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel
    
  cron:
    build:
      context: ./library_manager
      dockerfile: cron.Dockerfile
    volumes:
      - ./library_manager/cron/cronjob:/etc/cron.d/cronjob

volumes:
  db-data: ~

networks:
  laravel:
    driver: bridge