#version: "3.8"
#services:
#  php:
#    build:
#      context: .
#      target: php
#      args:
#        - APP_ENV=${APP_ENV}
#    environment:
#      - APP_ENV=${APP_ENV}
#      - CONTAINER_ROLE=app
#    working_dir: /var/www
#    volumes:
#      - ./:/var/www
#    ports:
#      - 8000:8000
#    depends_on:
#      - memcached
#      - database
#      - redis


#  database:
#    image: mariadb:latest
    #ports:
    #  - 3306:3306
#    environment:
#      - MYSQL_DATABASE=${DB_DATABASE}
#      - MYSQL_USER=${DB_USERNAME}
#      - MYSQL_PASSWORD=${DB_PASSWORD}
#      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
#    volumes:
#      - db-data:/var/lib/mysql
#      - /logs:/var/log/mysql


  #redis:
  #  image: redis:alpine
  #  command: redis-server --appendonly yes
    #ports:
    #  - 6379:6379

      
  #redis-commander:
  #  image: rediscommander/redis-commander:latest
  #  restart: always
  #  environment:
  #    - REDIS_HOSTS=local:redis:6379
  #  ports:
  #    - 8081:8081

  
  #memcached:
  #   image: memcached:latest
  #   environment:
  #    - MEMCACHED_PERSISTENT_ID=persistent_id
  #   ports:
  #    - 11211:11211

  #memcached:
  #  image: docker.io/bitnami/memcached:1
    #ports:
    #  - 11211:11211


  #admin:
  #  image: hatamiarash7/memcached-admin:latest
  #  environment:
  #    - MEMCACHED_HOST=memcached
  #    - MEMCACHED_PORT=11211
  #  ports:
  #    - 8085:80



  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin:latest
  #  restart: always
  #  ports:
  #    - 7000:80
  #  environment:
  #    - PMA_HOST=database
  #    - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}


  #networks:
  #  - laravel

#volumes:
#  db-data: ~

#networks:
#  laravel:
#    external: false
#    name: laravel
